# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

OHANA=ENV["OHANA"] || false
AVAHI="https://raw.githubusercontent.com/bigfix/boxes/master/vagrant/ready/scripts/avahi.sh"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bigfix/redhat70x64-server92"
  config.vm.hostname = "bigfix.test"

  config.vm.provider "virtualbox" do |v, override|
    v.gui = false
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]

    # http://serverfault.com/questions/495914/vagrant-slow-internet-connection-in-guest
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 52311, host: 52311
  config.vm.network :forwarded_port, guest: 80, host: 8080

  if OHANA
    config.vm.network :private_network, type: "dhcp"

    config.vm.provision "shell" do |s|
      s.path = AVAHI
    end
  end
end
