# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

BIGFIX_SERVER="https://raw.githubusercontent.com/bigfix/boxes/master/bigfix/redhat/server.sh"
BIGFIX_VERSION=[ENV["BIGFIX_VERSION"] || "9.2.0.363"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bigfix/redhat70x64-db2"
  config.vm.hostname = "bigfix-server.test"

  config.vm.provider "virtualbox" do |v, override|
    v.gui = false
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]

    # http://serverfault.com/questions/495914/vagrant-slow-internet-connection-in-guest
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.network :forwarded_port, guest: 52311, host: 52311
  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.vm.provision "shell" do |s|
    s.path = BIGFIX_SERVER
    s.args = BIGFIX_VERSION
  end
end
